#cloud-config
packages:
  - ca-certificates
  - curl
  - git
package_update: true
package_upgrade: true
runcmd:
  # Install docker
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  # Install Zabbix as a Docker container
  - mkdir -p /opt/zabbix && cd /opt/zabbix
  - git clone https://github.com/zabbix/zabbix-docker.git
  - cd zabbix-docker
  - git checkout 7.0
  - docker compose -f ./docker-compose_v3_alpine_mysql_latest.yaml --profile full up -d
  # Wait for Zabbix to start (sleep for 2 minutes)
  - sleep 120
  # Secure SSH
  - sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config
  - sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i 's/^#\?KbdInteractiveAuthentication.*/KbdInteractiveAuthentication no/' /etc/ssh/sshd_config
  - sed -i 's/^#\?ChallengeResponseAuthentication.*/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config
  - sed -i 's/^#\?MaxAuthTries.*/MaxAuthTries 3/' /etc/ssh/sshd_config
  # Reboot to apply all changes
  - reboot
